package com.ecommerce.paymentservice.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * Payment entity - records a payment transaction.
 *
 * In production, you would also store encrypted card details
 * or a token from your payment gateway (never raw card numbers).
 */
@Entity
@Table(name = "payments")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The order this payment is for */
    @Column(nullable = false)
    private Long orderId;

    /** Amount paid */
    @Column(nullable = false)
    private Double amount;

    /**
     * Payment method chosen by the user:
     * CREDIT_CARD, DEBIT_CARD, UPI, NET_BANKING
     */
    @Column(nullable = false)
    private String paymentMethod;

    /**
     * Payment status:
     * PENDING → COMPLETED (success) or FAILED
     * REFUNDED (if order cancelled)
     */
    @Column(nullable = false)
    @Builder.Default
    private String status = "PENDING";

    /**
     * Unique transaction ID generated by this service.
     * In production, this would come from the payment gateway.
     */
    private String transactionId;

    /** When the payment was processed */
    @Column(nullable = false)
    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();
}
